<a href="https://colab.research.google.com/github/szarina/IntroToAI/blob/main/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#1
for i in range(1,6):
    for j in range(1, i+1):
        print(j, end=" ")
    print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [5]:
#2
number = int(input())
sum = 0

for i in range(1, number + 1):
    sum += i

print(f"Sum is: {sum}")

10
Sum is: 55


In [14]:
#3
numbers = input("Enter a list of numbers separated by ,: ")
numbers = [int(num) for num in numbers.split(",")]

for number in numbers:
    if number > 500:
        break
    elif number % 5 == 0 and number <= 150:
        print(number)

Enter a list of numbers separated by ,: 12, 75, 150, 180, 145, 525, 50
75
150
145


In [10]:
#4
number = int(input("Enter a number: "))
digit_count = 0

while number > 0:
    number //= 10
    digit_count += 1

print(digit_count)

Enter a number: 3232
4


In [11]:
#5
for i in range(5, 0, -1):
    for j in range(i, 0, -1):
        print(j, end=" ")
    print()

5 4 3 2 1 
4 3 2 1 
3 2 1 
2 1 
1 


In [16]:
#6
numbers = input("Enter a list of numbers separated by ,: ")
numbers = [int(num) for num in numbers.split(",")]

for i in range(len(numbers) - 1, -1, -1):
    print(numbers[i])

Enter a list of numbers separated by ,: 10, 20, 30, 40, 50
50
40
30
20
10


In [17]:
#7
for i in range(-10, 0):
    print(i)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


In [19]:
#8
numbers = input("Enter a list of numbers separated by ,: ")
numbers = [int(num) for num in numbers.split(",")]

for i in range(1,len(numbers),2):
      print(numbers[i])

Enter a list of numbers separated by ,: 10, 20, 30, 40, 50, 60, 70, 80, 90, 100
20
40
60
80
100


In [22]:
#9
import numpy as np

sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])

# Original array
print("Printing Original array:")
print(sampleArray)

# Sorting the array by the second row
a = sampleArray[:, sampleArray[1, :].argsort()]
print("\nSorting Original array by second row:")
print(a)

# Sorting the array by the second column
b = sampleArray[sampleArray[:, 1].argsort()]
print("\nSorting Original array by second column:")
print(b)

Printing Original array:
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Sorting Original array by second row:
[[73 43 34]
 [12 22 82]
 [66 94 53]]

Sorting Original array by second column:
[[82 22 12]
 [34 43 73]
 [53 94 66]]


In [23]:
#10
import numpy as np

sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
newColumn = np.array([[10, 10, 10]])

# Printing Original array
print("Printing Original array:")
print(sampleArray)

# Deleting column 2
a = np.delete(sampleArray, 1, axis=1)
print("\nArray after deleting column 2:")
print(a)

# Inserting column 2
a = np.insert(a, 1, newColumn, axis=1)
print("\nArray after inserting column 2:")
print(a)

Printing Original array:
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Array after deleting column 2:
[[34 73]
 [82 12]
 [53 66]]

Array after inserting column 2:
[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [27]:
#11
import random
import string


letters = string.ascii_letters
random_string = ''.join(random.choice(letters) for _ in range(5))

print("Random String:", random_string)

Random String: HXAEG


In [31]:
#12
import random
import string

# Generating uppercase letters
uppercase_letters = ''.join(random.choices(string.ascii_uppercase, k = 2))

# Generating digits
digits = ''.join(random.choices(string.digits,k = 1))

# Generating symbols
symbols = ''.join(random.choices(string.punctuation,k = 1))

# Generating remaining 6 lowercase
remaining_chars = ''.join(random.choices(string.ascii_lowercase,k = 6))

password = uppercase_letters + digits + symbols + remaining_chars

# Shuffling
password_list = list(password)
random.shuffle(password_list)
final_password = ''.join(password_list)

#The final password
print(final_password)

z.fwEFqvm8
